import type { Metadata } from "next";
import { Geist, Quattrocento, Open_Sans ,Great_Vibes} from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const quattrocento = Quattrocento({
  variable: "--font-quattrocento",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const open_Sans = Open_Sans({
  variable: "--font-Open-Sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const great_Vibes = Great_Vibes({
  variable: "--font-Great_Vibes",
  subsets: ["latin"],
  weight: "400", // correct
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${quattrocento.variable} ${open_Sans.variable} ${great_Vibes.variable} antialiased`}
      >
        <div className="fixed top-0 z-40 w-full">
          <Navbar />
        </div>
        <main className="flex-1 pt-[4.2rem]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
